.travis.yml, README.md, REQUIRE, src/cholesky.jl, src/eigenGeneral.jl, src/eigenSelfAdjoint.jl, src/householder.jl, src/lapack.jl, src/qr.jl, src/svd.jl, test/REQUIRE, test/eigengeneral.jl, test/eigenselfadjoint.jl, test/qr.jl, test/runtests.jl, test/svd.jl, test/tridiag.jl
matrices.
Fix bug in bidiagonalization procedure for wide matrices
Suppert svdvals! for wide matrices by commenting out the check (it does
matter if the matrix is upper or lower when we only want the values)
Adjust convergence criterion. We now start with a zero shift so we should
be able to have high relative accuracy.
Remove outdated comments.
=> Extend Base's svdvals!. This allows e.g. cond and norm for BigFloat

src/eigenGeneral.jl, test/eigengeneral.jl
=> Add getproperty for Schur to extract Schur factor

src/eigenGeneral.jl, test/eigengeneral.jl
=> Set subdiagonal elements to zero when splitting in the general

Project.toml, src/svd.jl, test/svd.jl
istriu function since it's misleading for matrices where one of the
dimension sizes is just one. Closes #79
=> Test if SVD problem is tall or wide based on uplo field instead

src/svd.jl, test/svd.jl
There was an off-by-one indexing error such that the incorrect off-diagonal element was checked. This has probably caused unnecessary iterations and some cases and a complete convergence failure in #81 where the 2x2 block never gets detected.
Closes #81
=> Fix subproblem detection.

Project.toml, src/svd.jl, test/svd.jl
Found by @rabbott999 in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/81#issuecomment-1125082565
Closes https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/81
=> Fix typo in estimate_σ⁻

src/juliaBLAS.jl
- need to use the qualified names `BLAS.syrk!` and `BLAS.herk!`
- a large block of code is inside `if VERSION < v"1.3.0-alpha.115` but `Project.toml` gives the minimum Julia version as 1.6  I think that block should be dropped but I don't know what your policy regarding dropping dead code is.
=> syrk! and herk! are in the BLAS module

src/eigenGeneral.jl, src/svd.jl, test/eigengeneral.jl
By the Project.toml, the current version requires v1.6+, so some branches were unreachable.
=> Clean-up of version-dependent code

Project.toml, src/svd.jl
This is a companion PR to https://github.com/JuliaLang/julia/pull/46196. ~~It will fail for the nightly version until that PR is merged (if it gets merged).~~ It should no longer fail because it checks if `AdjointQ` is defined, independently from any versions. In principle, if we agree on merging the stdlib PR, we could merge this even before that PR, release a new version and then it should no longer fail on either `master` or `PR`.
=> Adjustment to `AdjointQ` introduction in LinearAlgebra

src/householder.jl, test/eigengeneral.jl
Also improve error messages and extend Base's convert instead of defining a new one
Fixes #100
=> Fix size of Householder

src/eigenGeneral.jl, src/eigenSelfAdjoint.jl, src/svd.jl
Also simplify code structure a bit in svd
=> Use logging system for debug printing

src/lapack.jl, test/lapack.jl
and fix some issues.
Closes https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/5
=> Improve some LAPACK test coverage

src/svd.jl, test/svd.jl
zero singular values
Closes #119
=> Test svd of zero matrix and fix the sign flipping when there are

src/svd.jl, test/svd.jl
=> Refactor code to avoid out of bounds operation after deflation

.github/workflows/ci.yml
This is necessary to upload coverage reports using the v4 of the Codecov action
=> Use JuliaLinearAlgebra's Codecov token in CI

.github/workflows/ci.yml
There seems to be a bug where Dependabot has trouble with `setup-julia@v2.2`, but does fine with `setup-julia@v2`. So let's just avoid the former.
=> CI: Change `setup-julia@v2.2` to `setup-julia@v2`

.github/workflows/Documenter.yml
In general, we should never use the `@latest` tag.
So let's switch to the `@v2` tag instead.
=> CI: Change `setup-julia@latest` to `setup-julia@v2`

src/eigenSelfAdjoint.jl, test/eigenselfadjoint.jl
=> Use eigencopy_oftype instead of copy_oftype

.github/workflows/ci.yml, src/eigenSelfAdjoint.jl, test/eigenselfadjoint.jl
They don't seem to be needed anymore and avoid an ambiguity introduced by Julia 1.11. Also, sort the eigenvalues of the symmetric problem when nothing is passed.
Fixes #141
=> Remove some pirated methods for the symmetric eigenvalue problem.

src/eigenGeneral.jl, src/eigenSelfAdjoint.jl, src/svd.jl
Profiling reveals that there is a lot of overhead from them even at the default logging level. Hopefully that will improve over time. For now, users would have to uncomment these lines before debugging.
As an example
```julia
julia> @btime GenericLinearAlgebra._eigen!(S) setup = (S = LinearAlgebra.SymTridiagonal(ones(100), 0.2*ones(99)));
505.083 μs (12 allocations: 159.12 KiB)
```
```julia
julia> @btime GenericLinearAlgebra._eigen!(S) setup = (S = LinearAlgebra.SymTridiagonal(ones(100), 0.2*ones(99)));
153.222 μs (12 allocations: 159.12 KiB)
```
=> Comment out @debug statements

src/eigenSelfAdjoint.jl, test/eigenselfadjoint.jl
symmetric solver
Some profiling revealed that the sorting used until this PR had significant overhead for smaller and medium sized problems. In addition, the values would be sorted twice if the user supplied a non-standard sorting function.
As an example
```julia
julia> @btime GenericLinearAlgebra._eigen!(S) setup = (S = LinearAlgebra.SymTridiagonal(ones(100), 0.2*ones(99)));
153.222 μs (12 allocations: 159.12 KiB)
```
```julia
julia> @btime GenericLinearAlgebra._eigen!(S) setup = (S = LinearAlgebra.SymTridiagonal(ones(100), 0.2*ones(99)));
45.367 μs (3 allocations: 78.57 KiB)
```
=> Rely on LinearAlgebra.eigsort! for sorting eigenvalues of the

.github/workflows/ci.yml, src/eigenSelfAdjoint.jl
While #147 isn't ready I think it's worth tolerating the `alg` kwarg so that it works on 1.12.
=> get it working on 1.12
